### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ryancheung** [Windmill-City/InputFix#1]
...

**Comment by Windmill-City** [comment]
最近正在重写text service framework的部分，应该可以解决这些奇怪的问题，毕竟我这边是可以运行的

**Comment by Windmill-City** [comment]
话说你现在写的Monogame.IMEHelper，还在使用IMM的函数，win10下不会闪退么....

**Comment by Windmill-City** [comment]
emm，我发现我的是1909，不过最近在重写tsf部分了，等我重写完再说吧

**Comment by ryancheung** [comment]
不会闪退，但是有BUG，打'ni'不会显示候选列表，调试了下发现是根本没有 IMM.ImeComposition 或 IMM.ImeStartCompostition 事件发送过来。除非使用纯IMM 实现的输入法，比如搜狗，或者在Win7上，就没有问题能正常使用。

原因我估计是Win 8 或 Win 10下以 IMM 方式启用 IME输入法就会有问题（除非使用纯IMM 实现的输入法），网上查到Win 8下这种方式启用IME更是一点反应都没。需要用你的方案（大神，膜拜）以TSF方式启用输入法，然后以 IMM composition event 获取候选词。

MonoGame 或 C# Winforms 手动渲染输入法太难了，直接用 IMM 的话 Win10 有BUG，TSF的话微软文档又少的可怜，C#这边就提都没提了。

另外，之前一直想解决 MonoGame 输入法问题，这是我的PR：https://github.com/MonoGame/MonoGame/pull/7118

现在准备用你的 TSF 方案启用输入法，但是对 TSF cpp 那边太陌生了，不知道大神您能否帮忙看一下，测试 repo: https://github.com/ryancheung/WindowsForms.IMEHelper.Core
基本思路就是，先用 cpp library 以 TSF 启用 IME，然后在 winforms 这边处理 IMM composition 或 WM_CHAR 事件获取候选列表或结果。

**Comment by ryancheung** [comment]
用搜狗输入法测试了下 InputFix，composition string 不能正常获取，能否做到可以和 Chrome 一样，不管是什么输入法，都能一样正常使用，比如获取comStr，候选词列表，设置输入发窗体位置。

**Comment by Windmill-City** [comment]
> 不会闪退，但是有BUG，打'ni'不会显示候选列表，打 'nihao' 才会出现候选列表。调试了下发现是根本没有 IMM.ImeComposition 或 IMM.ImeStartCompostition 事件发送过来。除非使用纯IMM 实现的输入法，比如搜狗，或者在Win7上，就没有问题能正常使用。
> 
> 原因我估计是Win 8 或 Win 10下以 IMM 方式启用 IME输入法就会有问题（除非使用纯IMM 实现的输入法），网上查到Win 8下这种方式启用IME更是一点反应都没。需要用你的方案（大神，膜拜）以TSF方式启用输入法，然后以 IMM composition event 获取候选词。
> 
> MonoGame 或 C# Winforms 手动渲染输入法太难了，直接用 IMM 的话 Win10 有BUG，TSF的话微软文档又少的可怜，C# Winforms 这边就提都没提了。
> 
> 另外，之前一直想解决 MonoGame 输入法问题，这是我的PR：[MonoGame/MonoGame#7118](https://github.com/MonoGame/MonoGame/pull/7118)
> 
> 现在准备用你的 TSF 方案启用输入法，但是对 TSF cpp 那边太陌生了，不知道大神您能否帮忙看一下，测试 repo: https://github.com/ryancheung/WindowsForms.IMEHelper.Core
> 基本思路就是，先用 cpp library 以 TSF 启用 IME，然后在 winforms 这边处理 IMM composition 或 WM_CHAR 事件获取候选列表或结果。

事实上你并不能既使用TSF又使用IMM，如果你要用TSF启动IME，那你就要在TSF里面处理事件，而不是监听IMM的事件

**Comment by Windmill-City** [comment]
> 用搜狗输入法测试了下 InputFix，composition string 不能正常获取，能否做到可以和 Chrome 一样，不管是什么输入法，都能一样正常使用，比如获取comStr，候选词列表，设置输入发窗体位置。
> 
> Google 找到以下 chromium 的 issue:
> https://bugs.chromium.org/p/chromium/issues/detail?id=657623
> https://bugs.chromium.org/p/chromium/issues/detail?id=963558
> 
> 实现源码:
> https://chromium.googlesource.com/chromium/src/+/6373124a3638f6c9f77c7914f78b226163973c68/ui/base/ime/win

最近已经在重写这部分代码了，之前的代码有些地方空着没实现（其实是不知道干嘛
等我再研究一下微软的文档，把旧代码重写一下再说吧

**Comment by ryancheung** [comment]
> 事实上你并不能既使用TSF又使用IMM，如果你要用TSF启动IME，那你就要在TSF里面处理事件，而不是监听IMM的事件

好吧，我只是看到 TextEdit.cpp 里面发了 WM_IME_STARTCOMPOSITION 和 WM_IME_COMPOSITION，消息，于是我这样改了下：
```
diff --git a/TSF/TextEdit.cpp b/TSF/TextEdit.cpp
index 33f6779..52ee9c2 100644
--- a/TSF/TextEdit.cpp
+++ b/TSF/TextEdit.cpp
@@ -127,14 +127,14 @@ STDMETHODIMP TextEdit::OnStartComposition(ITfCompositionView* pComposition, BOOL
 {
     OutputDebugString(TEXT("OnStartComposition\n"));
     *pfOk = TRUE;
-    SendMessage(m_hWnd, WM_IME_STARTCOMPOSITION, 0, 0);
+    SendMessage(m_hWnd, WM_IME_STARTCOMPOSITION, 0, 0x08);
     return S_OK;
 }

 STDMETHODIMP TextEdit::OnUpdateComposition(ITfCompositionView* pComposition, ITfRange* pRangeNew)    
 {
     OutputDebugString(TEXT("OnUpdateComposition\n"));
-    SendMessage(m_hWnd, WM_IME_COMPOSITION, 0, 0);
+    SendMessage(m_hWnd, WM_IME_COMPOSITION, 0, 0x08);
     return S_OK;
 }
```
就像 imm32 发的一样，只是 LParam 要改成 0x08。然后我去或许 candidate list，能 获取，只是有BUG，要打到 'nihaoa' 才能获取候选词列表。

**Comment by ryancheung** [comment]
https://yangyuan.github.io/post/2015-01-08-zh-meow-ime/
找到这篇，算是 TSF 和 IMM 的文档😄

**Comment by ryancheung** [comment]
@Windmill-City 我写了个这个 https://github.com/ryancheung/ImeSharp ，最新微软拼音支持没有问题，而且纯C#，不用写cpp clr.

**Comment by Windmill-City** [comment]
你看看我的libtf项目，里面有个C++的窗体程序，可以测试输入法，我没有2004版本测不了

**Comment by Windmill-City** [comment]
现在libtf已经完工了，就差一个CLI的兼容层就可以跑了

**Comment by Windmill-City** [comment]
libtf有3个事件:
onGetCompExt->获取composition字串的包围框
onCommitStr->输入法上屏的字串
onCompStr->输入法的composition的字串
输入法的候选词窗口是由输入法绘制的，就不用自己渲染了

**Comment by Windmill-City** [comment]
![image](https://user-images.githubusercontent.com/14292823/90027944-aa407e00-dceb-11ea-849e-d311fd251720.png)
这是我自己测试过的输入法，都是正常的
版本号1909|操在系统版本：18363.1016

**Comment by Windmill-City** [comment]
现在比较重要的问题：
1. TSF 似乎只能在STA线程创建的窗体下工作
2. boost::signals2 的connect函数如何传递C#的delegate指针

**Comment by Windmill-City** [comment]
也许是我机子的问题，ImeSharp.Demo一按F1就炸了

**Comment by ryancheung** [comment]
ImeSharp.Demo 不支持搜狗输入法，搜狗输入法不支持 `ITfCandidateListUIElementBehavior` com 接口，我刚刚修复了奔溃问题。因为我要自己渲染候选词列表，需要在全屏游戏里用，像魔兽世界怀旧服那样的，不需要系统渲染的。

**Comment by ryancheung** [comment]
> 输入法的候选词窗口是由输入法绘制的，就不用自己渲染了

我可能给你的需求不一样，我需要自己渲染候选词列表。
然后我不需要什么 TextStore，我只需要能拿到完整的 composition string 和候选词列表然后用事件丢出去用，就像IMM32的API一样。

**Comment by ryancheung** [comment]
> 1. TSF 似乎只能在STA线程创建的窗体下工作

TSF 只能在STA下工作，否则 QueryInterface 会找不到com object.



> 2\. boost::signals2 的connect函数如何传递C#的delegate指针

应该可以做到的，C# 的 delegate 函数指针可以丢给 cpp调用

**Comment by Windmill-City** [comment]
> > 输入法的候选词窗口是由输入法绘制的，就不用自己渲染了
> 
> 我可能跟你的需求不一样，我需要自己渲染候选词列表。
> 然后我不需要什么 TextStore，我只需要能拿到完整的 composition string 和候选词列表然后用事件丢出去用，就像IMM32的API一样。

但是TSF应该没有接口可以获取用户选择了哪个candidate吧
我也有实现ITfContextOwner，但是注册ITfTextEditSink是收不到上屏的数据的
所以一个TextStore应该是必要的

**Comment by ryancheung** [comment]
> 但是TSF应该没有接口可以获取用户选择了哪个candidate吧

可以的，在EndComposition () 里面，你可以调试运行下最新的IME sharp的Demo，可以正常获取composition，候选词列表，当前选中的候选词，result text。
事实上我实现的ITfContextOwner似乎没有效果，里面一个方法都不会调用，我把它删了估计都能正常运行，这里让我很困惑。。。

**Comment by Windmill-City** [comment]
> > 但是TSF应该没有接口可以获取用户选择了哪个candidate吧
> 
> 可以的，在EndComposition () 里面，你可以调试运行下最新的IME sharp的Demo，可以正常获取composition，候选词列表，当前选中的候选词，result text。
> 事实上我实现的ITfContextOwner似乎没有效果，里面一个方法都不会调用，我把它删了估计都能正常运行，这里让我很困惑。。。

那估计是新版改了，以前我获取的时候都是空的，不然我也不会去搞textstore这么麻烦的玩意了

**Comment by Windmill-City** [comment]
> 可以的，在EndComposition () 里面，你可以调试运行下最新的IME sharp的Demo，可以正常获取composition，候选词列表，当前选中的候选词，result text。

我这里测试还是不行
![image](https://user-images.githubusercontent.com/14292823/90081670-7f344980-dd40-11ea-8972-bd4da6b14853.png)

**Comment by Windmill-City** [comment]
要不你创个群，拉我进去，这里沟通有点麻烦

**Comment by Windmill-City** [comment]
> > 2. boost::signals2 的connect函数如何传递C#的delegate指针
> 
> 应该可以做到的，C# 的 delegate 函数指针可以丢给 cpp调用

我的signals2在release下运行报错，似乎是和运行库的设置有关

似乎是编译器的bug，这波凉了啊

**Comment by ryancheung** [comment]
来  Discord: https://discord.gg/BC4GKKr

**Comment by ryancheung** [comment]
> 我这里测试还是不行

你试试这个Example 行不行
[WindowsFormsApp1.zip](https://github.com/Windmill-City/InputFix/files/5066701/WindowsFormsApp1.zip)

有可能是 C# 这边用了 interface 继承导致的奔溃，如果上面项目不奔溃，那么应该就是这个问题
